### ISSUE TITLE
[Bug]: could not find driver

### ISSUE THREAD

**Issue by muhazmi** [teguh02/Indonesia-Territory-Forms#1]
### What happened?

i have problem with show the form with the error below:
![image](https://github.com/user-attachments/assets/2f539c6a-e876-498f-a38a-7afe268aadc3)

![image](https://github.com/user-attachments/assets/d9430809-014f-4ecb-89b5-dbf9c220361a)

![image](https://github.com/user-attachments/assets/bd1d2dbd-32b9-45ec-88fa-f89a1bcdb553)

### How to reproduce the bug

i already setup the .env like this:
```
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=filapos
DB_USERNAME=root
DB_PASSWORD=
```

### Package Version

1.1

### PHP Version

8.3.12

### Laravel Version

11.28.0

### Which operating systems does with happen with?

Linux

**Comment by teguh02** [comment]
Hi @muhazmi 
Thanks for your information for the bug. Can you make sure again do you have SQLite driver on your Linux machine? 
If you want you can run php -m and throw the output here. 

Thanks
Best Regards

**Comment by muhazmi** [comment]
I don't install it. Is it a must that i've to install SQLite?

**Comment by teguh02** [comment]
Yes you must. Because the data are Stored in the SQLite. I think i will update the documentation later to inform another people again. 

Thanks

**Comment by muhazmi** [comment]
I think it will be better if store the data into the same database.

**Comment by teguh02** [comment]
Sure thanks for the feedback. Maybe in the future version i will update it
Thanks
